### PR TITLE
Global 'error_channel' variable

### PR DESCRIPTION
**Pull request by Jejebecarte**
Instead of declaring 'error_channel' a very smooth 30 times, it's done once. (is updated for the rowdies + pb command)

### CODE REVIEW

**Comment by Leastrio** [comment]
I dont believe this works because it will try to get the channel out of cache before cache fills up, a fix for this could be using [wait_until_ready](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=wait_until_ready#discord.ext.commands.Bot.wait_until_ready)

**Review by Leastrio — CHANGES_REQUESTED** [review]
Make error_channel a bot var and set it to None. Then create a discord.ext task at the bottom that calls wait_until_ready and then fetches the channel which is set to the bot var. This also requires you to change every instance of calling error_message to calling client.error_message instead.

**Comment by Jejebecarte** [comment]
I tested the wrong file when I made it 😅... no wonder why it worked so well.

Anyway, instead of doing it the way you listed above I've opted for a more simple route, just updating the variable whenever needed, at first through the on_ready().

**Comment by Leastrio** [comment]
Doing stuff in on_ready is a bad idea, I would generally refrain from doing it in general.

**Comment by Jejebecarte** [comment]
Done. Thanks mate

**Review by Amxgh — APPROVED** [review]

**Pull request merged**
