### PR TITLE
make commands case insensitive

### PR DESCRIPTION
**Pull request by Fury-101**
cuz why not

### CODE REVIEW

**Comment by Leastrio** [comment]
why

**Comment by Fury-101** [comment]
why not

**Comment by Leastrio** [comment]
i think its useless lol

**Comment by Fury-101** [comment]
rowdies can stop going
aliases = ['gm','gM','Gm','GM','guildmember','gUIlDmEmber','guildMember','guiLdMemBer','g','G','gUILDMEMBER']

**Review by Amxgh — APPROVED** [review]

**Review by Amxgh — APPROVED** [review]

**Pull request merged**
