### PR TITLE
Rowdies

### PR DESCRIPTION
**Pull request by Fury-101**
Rowdies Rowdies Rowdies Rowdies Rowdies Rowdies Rowdies Rowdies Rowdies Rowdies Rowdies Rowdies

### CODE REVIEW

**Review by ElijahRus250 — COMMENTED** [review]
nice one @Amxgh

**Comment by Fury-101** [comment]
u should remove the code too btw cuz tos

**Review by Leastrio — CHANGES_REQUESTED** [review]
Wont work, ctx.author.id returns an int, and you are comparing it to a string

**Comment by Fury-101** [comment]
Noo too much smart

**Comment by Fury-101** [comment]
yeah so that didn't happen

**Pull request merged**
