### PR TITLE
DOGGO

### PR DESCRIPTION
**Pull request by Fury-101**
DOGGO
https://urmw.live/api/doggos/random

### CODE REVIEW

**Comment by ElijahRus250** [comment]
This wont work, https://urmw.live/api/doggos/random does not return valid json, you are trying to fetch an image that doesnt exist

**Comment by Leastrio** [comment]
not async smh

**Comment by Fury-101** [comment]
dont worry it works now i am just genius like that

**Comment by Fury-101** [comment]
wait crap

**Pull request closed without merging**
