### PR TITLE
Improve data file configuration

### PR DESCRIPTION
**Pull request by clwm**
Instead of having to rename the `TEMPLATE-` files.

To update the default files you can just force add the file to commit instead of having two versions of the same file.

### CODE REVIEW

**Review by Amxgh — COMMENTED** [review]
The template files are there so that testers know the format of the file when they decide to test the bot. .gitignored already had config.json but I forgot to add dnkl.json and eventparticipants.json.

**Comment by clwm** [comment]
> The template files are there so that testers know the format of the file
Are they not able to just look at the original version of the file? It still has the same contents as the template files.

**Comment by Amxgh** [comment]
The original version of .config has confidential stuff. The problem I'm facing is that we've linked the bot directly to GitHub, so, after every restart, the bot updates all files which results in it overriding any local changes it made. Unless you're able to suggest a solution for this, there's nothing I can do.

**Comment by clwm** [comment]
> we've linked the bot directly to GitHub

If you're using a service such as Heroku or similar and are importing the code from a repository you should try to utilize environment variables for private data.

**Comment by Amxgh** [comment]
@ElijahRus250

**Comment by clwm** [comment]
I'm going to close this because, obviously, a setup with environment variables would be ideal in your situation.

**Pull request closed without merging**
